version: "3.9"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/jar
    ports:
      - "8080:8080"
    # 환경변수 설정
    environment:
      - DBHOST=database
  db:
    image: mysql:8.0.32
    restart: always
    ports:
      - "3306:3306"	// mysql 기본 port
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop_study	// database 이름
      MYSQL_USER: root
      MYSQL_PASSWORD: xogns852
